#+TITLE:       List Comprehensions
#+AUTHOR:      Abram Hindle
#+DATE:        <2017-02-13 Mon>
#+EMAIL:       hindle1@ualberta.ca  
#+LANGUAGE:    language, e.g. ‘en’ (org-export-default-language)
#+OPTIONS:     exports:both
#+PROPERTY:  eval yes
#+PROPERTY:  exports both
#+PROPERTY: header-args    :results value raw
#+PROPERTY: header-args    :results output replace

* List Comprehensions
** Let's get a list of letters
    
    #+begin_src python :session
    asciis = range(ord("A"),ord("Z"))
    asciis
    #+end_src
    
    #+RESULTS:
    : 
    : [65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]

    
** Those aren't letters so how do we get letters back from them?
    
    #+begin_src python :session
    chr(asciis[0])
    #+end_src
    
    #+RESULTS:
    : 'A'


** Those aren't letters so how do we get letters back from them?
    
    #+begin_src python :session
    l = []
    for i in asciis:
        l.append(chr(i))
    
    l
    #+end_src
    
    #+RESULTS:
    : 
    : ... ... >>> ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y']
    
** That's a lot of code, if only it could be simpler!
   
   But it can be!
   
   #+begin_src python :session
   l2 = [chr(i) for i in asciis]
   
   l2
   #+end_src
   
   #+RESULTS:
   : 
   : >>> ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y']

** List Comprehensions
 
   - Use of a list comprehension as a mapping
   #+begin_src python
   [expression_of(a) for a in a_list]
   #+end_src

   - Use of a list comprehension as a mapping with a filter
   #+begin_src python
   [expression_of(a) for a in a_list if conditional_of(a)]
   #+end_src
   
** List Comprehensions (Mapping)
   - Let's try it out
   #+begin_src python :session
   a_list = range(0,10)
   expression_of = lambda x: 2*x
   l = [expression_of(a) for a in a_list]
   l
   #+end_src

   #+RESULTS:
   : 
   : >>> >>> [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

   - or directly 


   #+begin_src python :session
   l = [2*a for a in range(0,10)]
   l
   #+end_src

   #+RESULTS:
   : 
   : [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]




** List Comprehensions (Mapping and Filtering)
   - Let's try it out
   #+begin_src python :session
   a_list = range(0,10)
   expression_of = lambda x: 2*x
   condition_of = lambda x: x%2 == 0
   l = [expression_of(a) for a in a_list if condition_of(a)]
   l
   #+end_src

   #+RESULTS:
   : 
   : >>> >>> >>> [0, 4, 8, 12, 16]

   - or directly 

   #+begin_src python :session
   l = [2*a for a in range(0,10) if a%2 == 0]
   l
   #+end_src

   #+RESULTS:
   : [0, 4, 8, 12, 16]

   
** List Comprehensions Chaining

   You can chain the for calls. The precedence is confusing.

   #+begin_src python :session
   [str(outer) + str(inner) for outer in range(0,3) for inner in range(0,3)]
   #+end_src

   #+RESULTS:
   : ['00', '01', '02', '10', '11', '12', '20', '21', '22']

   You can filter too

   #+begin_src python :session
   [str(outer) + str(inner) for outer in range(0,3) if (outer+inner) % 2 == 0 for inner in range(0,3)]
   #+end_src

   #+RESULTS:
   : ['00', '01', '02', '20', '21', '22']

   But the order of filtering can be confusing

   #+begin_src python :session
   [str(outer) + str(inner) for outer in range(0,3) for inner in range(0,3) if (outer+inner) % 2 == 0 ]
   #+end_src

   #+RESULTS:
   : ['00', '02', '11', '20', '22']


** List Comprehensions Nesting

   You can nest list comprehensions. This enables multiple levels of
   mapping and filtering.

   #+begin_src python :session
   [str(outer) for outer in [inner+1 for inner in range(0,3)]]
   #+end_src

   #+RESULTS:
   : ['1', '2', '3']

   Let's go back to chaining and using nesting with chaining

   #+begin_src python :session
   [str(x[0])+str(x[1]) for x in 
       [(outer,inner) for outer in range(0,3) for inner in range(0,3)]
       if (x[0] + x[1])%2 == 0]
   #+end_src

   #+RESULTS:
   : 
   : ... ['00', '02', '11', '20', '22']

   or we can avoid indexing the tuple

   #+begin_src python :session
   [str(a)+str(b) for a, b in 
       [(outer,inner) for outer in range(0,3) for inner in range(0,3)]
       if (a + b)%2 == 0]
   #+end_src

   #+RESULTS:
   : 
   : ... ['00', '02', '11', '20', '22']

* List Comprehension Recipes
   


* Notes

C-c C-c this to stop confirmation on python

#+begin_src elisp
(defun my-org-confirm-babel-evaluate (lang body)
  (not (string= lang "python")))  ; don't ask for ditaa
(setq org-confirm-babel-evaluate 'my-org-confirm-babel-evaluate)
#+end_src

From orgmode http://orgmode.org/manual/Code-evaluation-security.html
Org-Mode Manual


** If you're really desperate with babel try this:

#+begin_src elisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)))
#+end_src

From Orgmode http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-python.html

